### ISSUE TITLE
sync posts from Facebook and twitter to rails app

### ISSUE THREAD

**Issue by ssoulless** [rdurgarao/Facebook-Twitter-posts-with-rails-example#1]
Hi, thanks for this great guide, I would like to ask if you have nay clues or resources on how to make the contrary, let me explain:

Let's say I have a model `Post` in my rails app, users can add posts, but how to publish in Facebook and also add a new post in the user account in my rails app?

I can't find any guides, or examples on how to achieve this. any ideas?

**Comment by rdurgarao** [comment]
Hi,

On Post Model add "after_create callback" and notify the changes to social channel

`Class Post`
`belongs_to :user`
`after_create :notify_to_social_channels`

`def notify_to_social_channels`
`// Implement the social integration logic`
`end`
`end`

`Class User`
`has_many :posts`
`end`

**Comment by ssoulless** [comment]
Thanks for your answer, but you misunderstood me.

first publish on Facebook, and then automatically publish in my app. is it clearer now?

**Comment by rdurgarao** [comment]
You can use before_create callback rather than after_create callback.
